version: "3.4"
services:
  webhookrelay:
    container_name: webhookrelay
    restart: unless-stopped
    image: sjafferali/portainer-github-webhook-relay:latest
    networks:
      proxy:
    environment:
      - PORTAINER_ENDPOINT=${PORTAINER_ENDPOINT}
      - PORTAINER_USERNAME=${PORTAINER_USERNAME}
      - PORTAINER_PASSWORD=${PORTAINER_PASSWORD}
      - PORTAINER_TOKEN_EXPIRATION=${PORTAINER_TOKEN_EXPIRATION}
      - STACK_CACHE_EXPIRATION=${STACK_CACHE_EXPIRATION}
networks:
  proxy:
    external: true
