import os

ENDPOINT = os.getenv("PORTAINER_ENDPOINT")
USERNAME = os.getenv("PORTAINER_USERNAME")
PASSWORD = os.getenv("PORTAINER_PASSWORD")
TOKEN_EXPIRATION = int(os.getenv("PORTAINER_TOKEN_EXPIRATION", 25200))
STACK_CACHE_EXPIRATION = int(os.getenv("PORTAINER_DATA_CACHE", 0))
